In [1]:
# Portfolio: Module 3 - NumPy Operations and Performance Comparison

import numpy as np
import time

print("--- TASK 17 & DATASET: Random Generation (Simulating Temperature Data) ---")
# Simulating daily temperature readings for 4 cities over 30 days
np.random.seed(42) # For reproducible results
temperatures = np.random.uniform(low=15.0, high=45.0, size=(4, 30))
print(f"Generated Temperature Data Shape: {temperatures.shape}")
print(f"First 3 days for City 1: {temperatures[0, :3].round(2)}\n")

print("--- TASK 12: Create and Manipulate Arrays (1D, 2D, 3D) ---")
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = temperatures # Our 2D dataset
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"1D Array Shape: {array_1d.shape}")
print(f"3D Array Shape: {array_3d.shape}\n")

print("--- TASK 13: Array Indexing, Slicing, and Reshaping ---")
# Slicing: Get temperatures for the first 2 cities, for the first 5 days
subset_temps = temperatures[:2, :5]
print("Subset (2 cities, 5 days):\n", subset_temps.round(1))

# Reshaping: Flatten the 4x30 array into a 1D array of 120 readings
flat_temps = temperatures.reshape(120)
print(f"\nReshaped to 1D: {flat_temps.shape}\n")

print("--- TASK 14: Mathematical Operations & Broadcasting ---")
# Element-wise: Convert Celsius to Fahrenheit: (C * 9/5) + 32
temps_fahrenheit = (temperatures * (9/5)) + 32

# Broadcasting: Add a specific baseline adjustment to each of the 4 cities
adjustments = np.array([[2.0], [-1.5], [0.5], [1.0]]) # Shape (4, 1)
adjusted_temps = temperatures + adjustments # Broadcasts across the 30 days
print("First day temperatures after broadcast adjustment:\n", adjusted_temps[:, 0].round(2), "\n")

print("--- TASK 15: Statistical Functions ---")
print(f"Overall Mean Temp: {np.mean(temperatures):.2f}°C")
print(f"Median Temp: {np.median(temperatures):.2f}°C")
print(f"Standard Deviation: {np.std(temperatures):.2f}")
print(f"90th Percentile: {np.percentile(temperatures, 90):.2f}°C")
print(f"Hottest day for City 1: {np.max(temperatures[0]):.2f}°C\n")

print("--- TASK 16: Linear Algebra Operations ---")
# Dot product and Matrix Multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_a, matrix_b)
print("Dot Product of A and B:\n", dot_product, "\n")

print("--- DELIVERABLE: Performance Comparison (NumPy vs Python Lists) ---")
# Creating a massive dataset to test speed
large_size = 1_000_000
python_list = list(range(large_size))
numpy_array = np.arange(large_size)

# Time Python Lists
start_time = time.time()
python_list_squared = [x**2 for x in python_list]
python_time = time.time() - start_time

# Time NumPy
start_time = time.time()
numpy_array_squared = numpy_array**2
numpy_time = time.time() - start_time

print(f"Pure Python List Time: {python_time:.5f} seconds")
print(f"NumPy Array Time: {numpy_time:.5f} seconds")
print(f"NumPy is {python_time / numpy_time:.2f}x faster!")

--- TASK 17 & DATASET: Random Generation (Simulating Temperature Data) ---
Generated Temperature Data Shape: (4, 30)
First 3 days for City 1: [26.24 43.52 36.96]

--- TASK 12: Create and Manipulate Arrays (1D, 2D, 3D) ---
1D Array Shape: (5,)
3D Array Shape: (2, 2, 2)

--- TASK 13: Array Indexing, Slicing, and Reshaping ---
Subset (2 cities, 5 days):
 [[26.2 43.5 37.  33.  19.7]
 [33.2 20.1 17.  43.5 44. ]]

Reshaped to 1D: (120,)

--- TASK 14: Mathematical Operations & Broadcasting ---
First day temperatures after broadcast adjustment:
 [28.24 31.73 27.16 19.59] 

--- TASK 15: Statistical Functions ---
Overall Mean Temp: 29.31°C
Median Temp: 29.49°C
Standard Deviation: 8.90
90th Percentile: 41.78°C
Hottest day for City 1: 44.10°C

--- TASK 16: Linear Algebra Operations ---
Dot Product of A and B:
 [[19 22]
 [43 50]] 

--- DELIVERABLE: Performance Comparison (NumPy vs Python Lists) ---
Pure Python List Time: 0.09238 seconds
NumPy Array Time: 0.00838 seconds
NumPy is 11.02x faster!
